In [14]:
import pandas as pd
import matplotlib.pyplot as plt
print("librairies importées avec succès.")

librairies importées avec succès.

In [16]:
df=pd.read_csv("../data/raw/autoconsommation_region.csv")
df.head()

  trimestre  code_region               nom_region  nombre_doperations_actives
0   2025-12           84     Auvergne-Rhône-Alpes                       239.0
1   2026-03           84     AUVERGNE RHONE ALPES                       297.0
2   2021-12           24      Centre-Val-de-Loire                         NaN
3   2026-03           27  BOURGOGNE FRANCHE COMTE                       171.0
4   2025-12           27  Bourgogne-Franche-Comté                       130.0

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trimestre                   252 non-null    str
 1   code_region                 252 non-null    int64
 2   nom_region                  252 non-null    str
 3   nombre_doperations_actives  231 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 13.6 KB

In [21]:
df.columns

Index(['trimestre', 'code_region', 'nom_region', 'nombre_doperations_actives'], dtype='str')

In [23]:
df.isna().sum()

trimestre                      0
code_region                    0
nom_region                     0
nombre_doperations_actives    21
dtype: int64

In [26]:
df[df["nombre_doperations_actives"].isna()]

,trimestre,code_region,nom_region,nombre_doperations_actives
2,2021-12,24,Centre-Val-de-Loire,NaN
18,2021-09,24,Centre-Val-de-Loire,NaN
46,2021-12,27,Bourgogne-Franche-Comté,NaN
48,2021-06,11,Île-de-France,NaN
76,2022-03,24,Centre-Val-de-Loire,NaN
78,2021-06,44,Grand-Est,NaN
90,2022-03,11,Île-de-France,NaN
98,2021-03,11,Île-de-France,NaN
105,2022-06,24,Centre-Val-de-Loire,NaN
112,2021-03,93,Provence-Alpes-Côte-d'Azur,NaN
126,2021-09,11,Île-de-France,NaN
128,2022-09,11,Île-de-France,NaN
132,2022-06,11,Île-de-France,NaN
140,2021-09,44,Grand-Est,NaN
142,2022-09,24,Centre-Val-de-Loire,NaN
151,2021-03,24,Centre-Val-de-Loire,NaN
178,2022-03,27,Bourgogne-Franche-Comté,NaN
180,2021-03,44,Grand-Est,NaN
216,2021-06,93,Provence-Alpes-Côte-d'Azur,NaN
238,2021-06,24,Centre-Val-de-Loire,NaN
239,2021-12,11,Île-de-France,NaN

In [28]:
df["nom_region"].unique()

<ArrowStringArray>
[      'Auvergne-Rhône-Alpes',       'AUVERGNE RHONE ALPES',
        'Centre-Val-de-Loire',    'BOURGOGNE FRANCHE COMTE',
    'Bourgogne-Franche-Comté',                   'BRETAGNE',
                   'Bretagne',                  'Normandie',
         'Nouvelle-Aquitaine',        'CENTRE VAL DE LOIRE',
                  'GRAND EST',                  'Occitanie',
                  'Grand-Est',            'Hauts-de-France',
           'Pays-de-la-Loire',            'HAUTS DE FRANCE',
              'Île-de-France',              'ILE DE FRANCE',
                  'NORMANDIE',         'NOUVELLE AQUITAINE',
                  'OCCITANIE',           'PAYS DE LA LOIRE',
 'Provence-Alpes-Côte-d'Azur', 'PROVENCE ALPES COTE D AZUR']
Length: 24, dtype: str

In [33]:
df["nom_region"].nunique()

24

In [35]:
df["code_region"].nunique()

12

In [37]:
df.groupby("code_region")["nom_region"].unique()

code_region
11                       [Île-de-France, ILE DE FRANCE]
24           [Centre-Val-de-Loire, CENTRE VAL DE LOIRE]
27    [BOURGOGNE FRANCHE COMTE, Bourgogne-Franche-Co...
28                               [Normandie, NORMANDIE]
32                   [Hauts-de-France, HAUTS DE FRANCE]
44                               [GRAND EST, Grand-Est]
52                 [Pays-de-la-Loire, PAYS DE LA LOIRE]
53                                 [BRETAGNE, Bretagne]
75             [Nouvelle-Aquitaine, NOUVELLE AQUITAINE]
76                               [Occitanie, OCCITANIE]
84         [Auvergne-Rhône-Alpes, AUVERGNE RHONE ALPES]
93    [Provence-Alpes-Côte-d'Azur, PROVENCE ALPES CO...
Name: nom_region, dtype: object

In [40]:
df_clean=df.copy()

In [44]:
region_mapping={
    11:"Île-de-France",
    24:"Centre-Val-de-Loire",
    27:"Bourgogne-Franche-Comté",
    28:"Normandie",
    32:"Hauts-de-France",
    44:"Grand-Est",
    52:"Pays-de-la-Loire",
    53:"Bretagne",
    75:"Nouvelle-Aquitaine",
    76:"Occitanie",
    84:"Auvergne-Rhônes-Alpes",
    93:"Provence-Alpes-Côte-d'Azur"
}
df_clean["nom_region_clean"]=df_clean["code_region"].map(region_mapping)

In [46]:
df_clean.groupby("code_region")["nom_region_clean"].unique()

code_region
11                 [Île-de-France]
24           [Centre-Val-de-Loire]
27       [Bourgogne-Franche-Comté]
28                     [Normandie]
32               [Hauts-de-France]
44                     [Grand-Est]
52              [Pays-de-la-Loire]
53                      [Bretagne]
75            [Nouvelle-Aquitaine]
76                     [Occitanie]
84         [Auvergne-Rhônes-Alpes]
93    [Provence-Alpes-Côte-d'Azur]
Name: nom_region_clean, dtype: object

In [48]:
df_clean["nom_region_clean"].unique()

<ArrowStringArray>
[     'Auvergne-Rhônes-Alpes',        'Centre-Val-de-Loire',
    'Bourgogne-Franche-Comté',                   'Bretagne',
                  'Normandie',         'Nouvelle-Aquitaine',
                  'Grand-Est',                  'Occitanie',
            'Hauts-de-France',           'Pays-de-la-Loire',
              'Île-de-France', 'Provence-Alpes-Côte-d'Azur']
Length: 12, dtype: str

In [52]:
df_clean["operation_valeur_manquantes"]=df_clean["nombre_doperations_actives"].isna()

In [56]:
df_clean["nombre_doperations_actives_clean"]=(
    df_clean["nombre_doperations_actives"]
    .fillna(0)
    .astype(int)
)

In [81]:
df_clean["trimestre_date"] = pd.to_datetime(
    df_clean["trimestre"],
    errors="coerce"
)

In [82]:
df_clean[["trimestre", "trimestre_date"]].head(10)

  trimestre trimestre_date
0   2025-12     2025-12-01
1   2026-03     2026-03-01
2   2021-12     2021-12-01
3   2026-03     2026-03-01
4   2025-12     2025-12-01
5   2025-06     2025-06-01
6   2026-03     2026-03-01
7   2025-12     2025-12-01
8   2023-03     2023-03-01
9   2023-12     2023-12-01

In [78]:
df_clean["nom_region_clean"]

0           Auvergne-Rhônes-Alpes
1           Auvergne-Rhônes-Alpes
2             Centre-Val-de-Loire
3         Bourgogne-Franche-Comté
4         Bourgogne-Franche-Comté
                  ...
247                     Normandie
248                     Occitanie
249    Provence-Alpes-Côte-d'Azur
250                     Grand-Est
251              Pays-de-la-Loire
Name: nom_region_clean, Length: 252, dtype: str

In [84]:
df_clean["année"]= df_clean["trimestre_date"].dt.year

In [87]:
df_clean["trimestre_date"].isna()

0      False
1      False
2      False
3      False
4      False
       ...
247    False
248    False
249    False
250    False
251    False
Name: trimestre_date, Length: 252, dtype: bool

In [89]:
df_clean["nombre_doperations_actives_clean"].isna().sum()

np.int64(0)

In [91]:
df_clean[df_clean["nombre_doperations_actives"].isna()]

,trimestre,code_region,nom_region,nombre_doperations_actives,nom_region_clean,operation_valeur_manquantes,nombre_doperations_actives_clean,trimestre_date,année
2,2021-12,24,Centre-Val-de-Loire,NaN,Centre-Val-de-Loire,True,0,2021-12-01,2021
18,2021-09,24,Centre-Val-de-Loire,NaN,Centre-Val-de-Loire,True,0,2021-09-01,2021
46,2021-12,27,Bourgogne-Franche-Comté,NaN,Bourgogne-Franche-Comté,True,0,2021-12-01,2021
48,2021-06,11,Île-de-France,NaN,Île-de-France,True,0,2021-06-01,2021
76,2022-03,24,Centre-Val-de-Loire,NaN,Centre-Val-de-Loire,True,0,2022-03-01,2022
78,2021-06,44,Grand-Est,NaN,Grand-Est,True,0,2021-06-01,2021
90,2022-03,11,Île-de-France,NaN,Île-de-France,True,0,2022-03-01,2022
98,2021-03,11,Île-de-France,NaN,Île-de-France,True,0,2021-03-01,2021
105,2022-06,24,Centre-Val-de-Loire,NaN,Centre-Val-de-Loire,True,0,2022-06-01,2022
112,2021-03,93,Provence-Alpes-Côte-d'Azur,NaN,Provence-Alpes-Côte-d'Azur,True,0,2021-03-01,2021
126,2021-09,11,Île-de-France,NaN,Île-de-France,True,0,2021-09-01,2021
128,2022-09,11,Île-de-France,NaN,Île-de-France,True,0,2022-09-01,2022
132,2022-06,11,Île-de-France,NaN,Île-de-France,True,0,2022-06-01,2022
140,2021-09,44,Grand-Est,NaN,Grand-Est,True,0,2021-09-01,2021
142,2022-09,24,Centre-Val-de-Loire,NaN,Centre-Val-de-Loire,True,0,2022-09-01,2022
151,2021-03,24,Centre-Val-de-Loire,NaN,Centre-Val-de-Loire,True,0,2021-03-01,2021
178,2022-03,27,Bourgogne-Franche-Comté,NaN,Bourgogne-Franche-Comté,True,0,2022-03-01,2022
180,2021-03,44,Grand-Est,NaN,Grand-Est,True,0,2021-03-01,2021
216,2021-06,93,Provence-Alpes-Côte-d'Azur,NaN,Provence-Alpes-Côte-d'Azur,True,0,2021-06-01,2021
238,2021-06,24,Centre-Val-de-Loire,NaN,Centre-Val-de-Loire,True,0,2021-06-01,2021
239,2021-12,11,Île-de-France,NaN,Île-de-France,True,0,2021-12-01,2021

In [93]:
df_clean.columns

Index(['trimestre', 'code_region', 'nom_region', 'nombre_doperations_actives',
       'nom_region_clean', 'operation_valeur_manquantes',
       'nombre_doperations_actives_clean', 'trimestre_date', 'année'],
      dtype='str')

In [96]:
df_clean=df_clean.rename(columns={"année":"annee"})

In [99]:
df_clean.columns

Index(['trimestre', 'code_region', 'nom_region', 'nombre_doperations_actives',
       'nom_region_clean', 'operation_valeur_manquantes',
       'nombre_doperations_actives_clean', 'trimestre_date', 'annee'],
      dtype='str')

In [102]:
df_powerbi=df_clean[
    ["trimestre_date",
     "annee",
     "code_region",
     "nom_region_clean",
     "nombre_doperations_actives_clean",
     "operation_valeur_manquantes"
    ]
    ].copy()

In [105]:
df_powerbi.head()

,trimestre_date,annee,code_region,nom_region_clean,nombre_doperations_actives_clean,operation_valeur_manquantes
0,2025-12-01,2025,84,Auvergne-Rhônes-Alpes,239,False
1,2026-03-01,2026,84,Auvergne-Rhônes-Alpes,297,False
2,2021-12-01,2021,24,Centre-Val-de-Loire,0,True
3,2026-03-01,2026,27,Bourgogne-Franche-Comté,171,False
4,2025-12-01,2025,27,Bourgogne-Franche-Comté,130,False

In [108]:
df_powerbi=df_powerbi.rename(columns={
    "nom_region_clean":"nom_region",
    "nombre_doperations_actives_clean":"operations_actives",
    "operation_valeur_manquantes":"valeur_operation_manquante"
})

In [110]:
df_powerbi.head()

,trimestre_date,annee,code_region,nom_region,operations_actives,valeur_operation_manquante
0,2025-12-01,2025,84,Auvergne-Rhônes-Alpes,239,False
1,2026-03-01,2026,84,Auvergne-Rhônes-Alpes,297,False
2,2021-12-01,2021,24,Centre-Val-de-Loire,0,True
3,2026-03-01,2026,27,Bourgogne-Franche-Comté,171,False
4,2025-12-01,2025,27,Bourgogne-Franche-Comté,130,False

In [112]:
df_powerbi.info()

<class 'pandas.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trimestre_date              252 non-null    datetime64[us]
 1   annee                       252 non-null    int32
 2   code_region                 252 non-null    int64
 3   nom_region                  252 non-null    str
 4   operations_actives          252 non-null    int64
 5   valeur_operation_manquante  252 non-null    bool
dtypes: bool(1), datetime64[us](1), int32(1), int64(2), str(1)
memory usage: 13.2 KB

In [115]:
df_powerbi.to_csv(
    "../data/processed/autoconsommation_region_clean.csv",
    index=False,
    encoding ="utf-8-sig"
)

In [117]:
from pathlib import Path
Path("../data/processed/autoconsommation_region_clean.csv").exists()

True

In [120]:
df_powerbi["periode"]=df_powerbi["trimestre_date"].dt.to_period("Q").astype(str)

In [124]:
df_powerbi[["periode","trimestre_date"]]

    periode trimestre_date
0    2025Q4     2025-12-01
1    2026Q1     2026-03-01
2    2021Q4     2021-12-01
3    2026Q1     2026-03-01
4    2025Q4     2025-12-01
..      ...            ...
247  2025Q3     2025-09-01
248  2025Q3     2025-09-01
249  2025Q3     2025-09-01
250  2025Q3     2025-09-01
251  2025Q3     2025-09-01

[252 rows x 2 columns]

In [126]:
df_powerbi.to_csv(
    "../data/processed/autoconsommation_region_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

In [127]:
test = pd.read_csv("../data/processed/autoconsommation_region_clean.csv")
test.columns

Index(['trimestre_date', 'annee', 'code_region', 'nom_region',
       'operations_actives', 'valeur_operation_manquante', 'periode'],
      dtype='str')